name: Build SVT-AV1-PSY on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Build Windows Binary
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install NASM
        run: |
          choco install nasm -y
          refreshenv

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Configure with CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build with MSBuild
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload built executable
        uses: actions/upload-artifact@v4
        with:
          name: svt-av1-psy-exe
          path: build/Bin/Release/SvtAv1EncApp.exe
